# Argo CD Helm Chart Values
# Source: https://github.com/argoproj/argo-helm/tree/main/charts/argo-cd
# Deployed via: ./bootstrap/install.sh stag

global:
  domain: hayes-argocd-stag.hayesinc.com
  environment: stag

argo-cd:
  server:
    replicas: 2

    ingress:
      enabled: false

    extraArgs:
      - --insecure

  repoServer:
    replicas: 2

  controller:
    replicas: 1

  redis-ha:
    enabled: false

  redis:
    enabled: true

  configs:
    params:
      server.insecure: true

    cm:
      accounts.admin: apiKey, login
      admin.enabled: "true"

      url: http://localhost:8080

      dex.config: |
        connectors:
          - type: github
            id: github
            name: GitHub
            config:
              clientID: Ov23liN2SIikmVhv4l0h
              clientSecret: $dex.github.clientSecret

    rbac:
      policy.default: role:admin

    secret:
      createSecret: true
      extra:
        dex.github.clientSecret: cdbd7a8c7ab254a51f89d4b8b34d76a9dfc18f6f

  applicationSet:
    replicas: 2

  notifications:
    enabled: false
