# Argo CD Values - DEV Environment
# Cluster: symplr-hayes-dev-eks-cluster

global:
  domain: hayes-argocd-dev.hayesinc.com
  environment: dev

server:
  replicas: 1

  ingress:
    enabled: false

  extraArgs:
    - --insecure

repoServer:
  replicas: 1

controller:
  replicas: 1

redis-ha:
  enabled: false

redis:
  enabled: true

configs:
  params:
    server.insecure: true

  cm:
    accounts.admin: apiKey, login
    admin.enabled: "true"
    url: https://hayes-argocd-dev.hayesinc.com

  rbac:
    policy.default: role:readonly
    policy.csv: |
      g, admin, role:admin

  secret:
    createSecret: true

applicationSet:
  replicas: 1

notifications:
  enabled: false

ingress:
  certificateArn: ""
  albGroupName: symplr-hayes-dev-eks-alb
